### ISSUE TITLE
Crop button missing

### ISSUE THREAD

**Issue by gustaveracosta** [ian-hamlin/Xamarin.ArthurHub.Android-Image-Cropper#4]
I am able to see the picture taken then the crop bound box appears but there is no "Crop Button". Thus, only way to return to invoking activity is by pressing the back key which cancels the process. Such a good library but can't be used because of this!

**Comment by gustaveracosta** [comment]
I found the problem. My app does not implement toolbar. So I can't use your library I suppose. Would be nice to have options to use your library without actionbar.

**Comment by ian-hamlin** [comment]
Hello, those are just the defaults, you can provide your own buttons if you wish.  For more information view the original Java Library [https://github.com/ArthurHub/Android-Image-Cropper] or have a look at this blog post, as they are using custom buttons:

https://theartofdev.com/2016/01/15/android-image-cropper-async-support-and-custom-progress-ui/
