### ISSUE TITLE
Exception being throw by Image Cropper library

### ISSUE THREAD

**Issue by gilles-leblanc** [ian-hamlin/Xamarin.ArthurHub.Android-Image-Cropper#5]
When targetting SDK level 28 or higher, calling `CropImageView`'s `SetCropShape` with `CropImageView.CropShape.Oval` results in an `java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed` exception.

At:
` at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
    at android.graphics.Canvas.clipPath(Canvas.java:1007)
    at com.theartofdev.edmodo.cropper.CropOverlayView.drawBackground(CropOverlayView.java:635)
    at com.theartofdev.edmodo.cropper.CropOverlayView.onDraw(CropOverlayView.java:579)`

This was working correctly while targeting earlier SDK versions. 

After a quick investigation this is because ArthurHub/Android-Image-Cropper 2.7.0 (which is used by the binding) uses `Region.Op.XOR` which isn't supported anymore.
https://github.com/ArthurHub/Android-Image-Cropper/blob/092a39533aa760472299a442773c7e2eee404de8/cropper/src/main/java/com/theartofdev/edmodo/cropper/CropOverlayView.java#L635

This has been fixed in the 2.8.0 version of the library and it is compatible with SDK level 28. 
To fix this issue, the bindings would need to be updated to the 2.8.0 version.

I tried updating the bindings myself by forking the project, but I've run into the problem where most of the classes don't appear in the final binding or the api.xml file so it's not working.

**Comment by ian-hamlin** [comment]
Thanks for raising this, I will take a look.

**Comment by gilles-leblanc** [comment]
I got it to work today by targetting Android 8.0 in the bindings project instead of 8.1 and using class-parser instead of jar2xml.
